---
apiVersion: api-gateway.consul.hashicorp.com/v1alpha1
kind: GatewayClassConfig
metadata:
  name: default-consul-gateway-class-config
spec:
  serviceType: LoadBalancer
  consul:
    scheme: https
    caSecret: consul-ca-cert
    ports:
      http: 8501
      grpc: 8502