# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

---
apiVersion: api-gateway.consul.hashicorp.com/v1alpha1
kind: GatewayClassConfig
metadata:
  name: default-consul-gateway-class-config
spec:
  serviceType: LoadBalancer
  consul:
    scheme: https
    ports:
      http: 8501
      grpc: 8502
