name: "Tear down EKS"
description: "Tears down an EKS cluster. Requires eksctl and credentials in the workflow's environment from the setup-eks action."
inputs:
  cluster_name:
    description: "The name assigned to the EKS cluster"
    required: true
  region:
    description: "The AWS region that the cluster was created in"
    required: false
    default: us-west-2
runs:
  using: composite
  steps:
    - name: Delete EKS cluster
      shell: bash
      env:
        AWS_EC2_METADATA_DISABLED: true
      run: |
      
        set +e 

        for each in $(kubectl get ns -o jsonpath="{.items[*].metadata.name}" | grep -v kube-system);
        do
          kubectl delete --all svc --namespace $each
        done

        eksctl delete cluster --name ${{ inputs.cluster_name }} --region ${{ inputs.region}} --parallel 3 --force --wait

        #if unsuccesful, run delete again to account for race condition
        if [ $? -eq 1 ]; then
          eksctl delete cluster --name ${{ inputs.cluster_name }} --region ${{ inputs.region}} --parallel 3 --force --wait
        fi
