# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: 2
updates:
  - package-ecosystem: gomod
    open-pull-requests-limit: 5
    directory: "/"
    labels:
      - "dependencies"
      - "pr/no-changelog"
    schedule:
      interval: daily
