// Package internal provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/andrewstucki/oapi-codegen version v1.10.2-0.20220902020913-b36ba463f350 DO NOT EDIT.
package internal

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
)

// Start of User Generated Client

type UnexpectedResponse struct {
	code int
	body string
}

func NewUnexpectedResponse(code int, body []byte) *UnexpectedResponse {
	return &UnexpectedResponse{
		code: code,
		body: string(body),
	}
}

func (e *UnexpectedResponse) Error() string {
	return fmt.Sprintf("server response could not be parsed - code: %d, message: %s", e.code, e.body)
}

func (e *Error) Error() string {
	return fmt.Sprintf("server error - code: %d, message: %s", e.Code, e.Message)
}

func IsNotFound(e error) bool {
	var err *Error
	if errors.As(e, &err) {
		return err.Code == http.StatusNotFound
	}
	return false
}

func (c *APIClient) Bootstrap(ctx context.Context) (*BootstrapConfiguration, error) {

	resp, err := c.client.BootstrapWithResponse(ctx)
	if err != nil {
		return nil, err
	}
	if resp.JSONDefault != nil {
		return nil, resp.JSONDefault
	}
	if resp.JSON200 != nil {
		return resp.JSON200, nil
	}
	return nil, NewUnexpectedResponse(resp.StatusCode(), resp.Body)
}

// End of User Generated Client

// Start generated server helpers

func sendError(w http.ResponseWriter, code int, message string) {
	send(w, code, Error{
		Code:    int32(code),
		Message: message,
	})
}

func send(w http.ResponseWriter, code int, object interface{}) {
	w.WriteHeader(code)
	json.NewEncoder(w).Encode(object)
}

func sendEmpty(w http.ResponseWriter, code int) {
	w.WriteHeader(code)
	w.Write([]byte("{}\n"))
}

// End generated server helpers
