# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - unconvert
    - staticcheck
    - ineffassign
    - unparam
    - unused

issues:
  # Disable the default exclude list so that all excludes are explicitly
  # defined in this file.
  exclude-use-default: false

  exclude-rules:
    # maybe some stuff here

linters-settings:
  gofmt:
    simplify: true

run:
  concurrency: 2
  timeout: 10m
