# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

blank_issues_enabled: false
contact_links:
  - name: Consul Discuss Forum
    url: https://discuss.hashicorp.com/c/consul
    about: Please check out our discussion forum. Ask a question or see if yours has already been answered there.