# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: v1
kind: Secret
metadata:
  name: consul-api-gateway
  annotations:
    kubernetes.io/service-account.name: consul-api-gateway
type: kubernetes.io/service-account-token
