apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubernetes-sigs/gateway-api/config/crd/experimental?ref=v0.5.0-rc2
- https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v0.5.0-rc2/config/crd/experimental/gateway.networking.k8s.io_referencepolicies.yaml
- bases/api-gateway.consul.hashicorp.com_gatewayclassconfigs.yaml
- bases/api-gateway.consul.hashicorp.com_meshservices.yaml
