apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubernetes-sigs/gateway-api/config/crd?ref=v0.4.0
- bases/api-gateway.consul.hashicorp.com_gatewayclassconfigs.yaml