// Code generated by MockGen. DO NOT EDIT.
// Source: ./middleware.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	common "github.com/hashicorp/polar/internal/common"
)

// MockGatewaySecretRegistry is a mock of GatewaySecretRegistry interface.
type MockGatewaySecretRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockGatewaySecretRegistryMockRecorder
}

// MockGatewaySecretRegistryMockRecorder is the mock recorder for MockGatewaySecretRegistry.
type MockGatewaySecretRegistryMockRecorder struct {
	mock *MockGatewaySecretRegistry
}

// NewMockGatewaySecretRegistry creates a new mock instance.
func NewMockGatewaySecretRegistry(ctrl *gomock.Controller) *MockGatewaySecretRegistry {
	mock := &MockGatewaySecretRegistry{ctrl: ctrl}
	mock.recorder = &MockGatewaySecretRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGatewaySecretRegistry) EXPECT() *MockGatewaySecretRegistryMockRecorder {
	return m.recorder
}

// CanFetchSecrets mocks base method.
func (m *MockGatewaySecretRegistry) CanFetchSecrets(info common.GatewayInfo, secrets []string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanFetchSecrets", info, secrets)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanFetchSecrets indicates an expected call of CanFetchSecrets.
func (mr *MockGatewaySecretRegistryMockRecorder) CanFetchSecrets(info, secrets interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanFetchSecrets", reflect.TypeOf((*MockGatewaySecretRegistry)(nil).CanFetchSecrets), info, secrets)
}

// GatewayExists mocks base method.
func (m *MockGatewaySecretRegistry) GatewayExists(info common.GatewayInfo) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GatewayExists", info)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GatewayExists indicates an expected call of GatewayExists.
func (mr *MockGatewaySecretRegistryMockRecorder) GatewayExists(info interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GatewayExists", reflect.TypeOf((*MockGatewaySecretRegistry)(nil).GatewayExists), info)
}
