url_docker_registry_dockerhub = "https://hub.docker.com/r/hashicorp/consul-api-gateway"
url_license = "https://github.com/hashicorp/consul-api-gateway/blob/main/LICENSE.md"
url_project_website = "https://www.consul.io/docs/api-gateway"
url_release_notes = "https://www.consul.io/docs/release-notes"
url_source_repository = "https://github.com/hashicorp/consul-api-gateway"
