# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificates.yaml
- external-dns.yaml
- gateway.yaml
- service.yaml
- route.yaml