name: docker

on:
  push:
    branches: ["main", "dev-image-main"]  # TODO Remove before merge

jobs: 
  build-dev-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        goos: ["linux"]
        goarch: ["amd64"]
        go: ["1.17"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p dist/linux/${{ matrix.goarch }}
          go build -o dist/linux/${{ matrix.goarch }}

      - name: Get product version
        id: get-product-version
        run: echo "::set-output name=product-version::$(make version)"

      - name: Build Docker image
        uses: hashicorp/actions-docker-build@v1
        env:
          PRODUCT_NAME: ${{ github.event.repository.name }}
          PRODUCT_VERSION: ${{ steps.get-product-version.outputs.product-version }}
        with:
          target: default
          arch: ${{ matrix.goarch }}
          version: ${{ steps.get-product-version.outputs.product-version }}
          bin_name: "consul-api-gateway"
          dev_tags: |
            hashicorppreview/${{ env.PRODUCT_NAME }}:${{ env.PRODUCT_VERSION }}-dev
            hashicorppreview/${{ env.PRODUCT_NAME }}:${{ env.PRODUCT_VERSION }}-${{ github.sha }}
