name: prepare_release

on:
  workflow_dispatch:
    inputs:
      new-min-consul-version:
        description: 'The new minimum version of Consul (no "v" prefix)'
        required: true
        type: string
      new-min-consul-k8s-version:
        description: 'The new minimum version of Consul K8s (no "v" prefix)'
        required: true
        type: string

jobs:
  update-versions:
    runs-on: ubuntu-latest
    env:
      NEW_CONSUL_REQ: ${{ github.event.inputs.new-min-consul-version }}
      NEW_CONSUL_K8S_REQ: ${{ github.event.inputs.new-min-consul-k8s-version }}

    steps:

      - name: Checkout consul-api-gateway
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Set version being released
        run: |
          VERSION=$(make version)
          echo "NEW_API_GATEWAY_VERSION<<EOF" >> $GITHUB_ENV
          echo "$VERSION" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update deployment.yaml
        uses: jacobtomlinson/gha-find-replace@f485fdc3f67a6d87ae6e3d11e41f648c26d7aee3
        with:
          include: config/deployment/deployment.yaml
          find: 'image: hashicorp/consul-api-gateway:[0-9\.]+'
          replace: 'image: hashicorp/consul-api-gateway:${{ env.NEW_API_GATEWAY_VERSION }}'

      - name: Update example-setup.md
        uses: jacobtomlinson/gha-find-replace@f485fdc3f67a6d87ae6e3d11e41f648c26d7aee3
        with:
          include: 'dev/docs/example-setup.md'
          find: 'ref=v[0-9\.]+'
          replace: 'ref=v${{ env.NEW_API_GATEWAY_VERSION }}'

      - name: Update supported-features.md
        uses: jacobtomlinson/gha-find-replace@f485fdc3f67a6d87ae6e3d11e41f648c26d7aee3
        with:
          include: 'dev/docs/supported-features.md'
          find: 'Consul API Gateway version: \*\*v[0-9\.]+\*\*'
          replace: 'Consul API Gateway version: **v${{ env.NEW_API_GATEWAY_VERSION }}**'

      - name: Update README.md (Consul version)
        uses: jacobtomlinson/gha-find-replace@f485fdc3f67a6d87ae6e3d11e41f648c26d7aee3
        with:
          include: 'README.md'
          find: 'The installed version of Consul must be `v[0-9\.]+` or greater.'
          replace: 'The installed version of Consul must be `v${{ env.NEW_CONSUL_REQ }}` or greater.'

      - name: Update README.md (Consul K8s version)
        uses: jacobtomlinson/gha-find-replace@f485fdc3f67a6d87ae6e3d11e41f648c26d7aee3
        with:
          include: 'README.md'
          find: 'The Consul Helm chart must be version `[0-9\.]+` or greater.'
          replace: 'The Consul Helm chart must be version `${{ env.NEW_CONSUL_K8S_REQ }}` or greater.'

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Regenerate golden files
        run: make generate-golden-files

      - name: Get current date
        id: get-current-date
        run: echo "::set-output name=date::$(date +'%B %d, %Y')"

      - name: Generate changelog patch
        id: generate-changelog-patch
        run: | # Pass via environment variable to keep multiline in tact
          export LAST_RELEASE_GIT_TAG=$(git tag --sort=committerdate | tail -1)
          CHANGELOG_PATCH=$(make changelog)
          echo "CHANGELOG_PATCH<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG_PATCH" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update CHANGELOG.md
        uses: jacobtomlinson/gha-find-replace@f485fdc3f67a6d87ae6e3d11e41f648c26d7aee3
        with:
          include: 'CHANGELOG.md'
          find: |
            ## UNRELEASED

          replace: |
            ## UNRELEASED
            
            ## ${{ env.NEW_API_GATEWAY_VERSION }} (${{ steps.get-current-date.outputs.date }})
            ${{ env.CHANGELOG_PATCH }}
          regex: false

      - name: Create pull request
        id: create-pr
        uses: peter-evans/create-pull-request@923ad837f191474af6b1721408744feb989a4c27
        with:
          body: |
            Consul API Gateway version being released: `${{ env.NEW_API_GATEWAY_VERSION }}`
            Now requires:
            - consul: `${{ env.NEW_CONSUL_REQ }}`
            - consul-k8s: `${{ env.NEW_CONSUL_K8S_REQ }}`
          branch: 'v${{ env.NEW_API_GATEWAY_VERSION }}-release-prep'
          commit-message: |
            Prepare for release of v${{ env.NEW_API_GATEWAY_VERSION }}
            Consul API Gateway version being released: `${{ env.NEW_API_GATEWAY_VERSION }}`
            Now requires:
            - consul: `${{ env.NEW_CONSUL_REQ }}`
            - consul-k8s: `${{ env.NEW_CONSUL_K8S_REQ }}`
          delete-branch: true
          labels: 'pr/no-changelog'
          title: 'Prepare for release of v${{ env.NEW_API_GATEWAY_VERSION }}'
          token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}

      - name: Output link to PR
        run: echo '[Resulting PR](${{ steps.create-pr.outputs.pull-request-url }})' >> $GITHUB_STEP_SUMMARY
